# Generated by Django 2.2 on 2020-04-14 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pic', models.URLField()),
                ('date_time', models.DateTimeField()),
                ('details', models.TextField()),
                ('entryfee', models.PositiveSmallIntegerField()),
                ('venue', models.CharField(default=None, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('deadline', models.DateTimeField()),
                ('submitinfo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.URLField(max_length=1000)),
                ('tagline', models.CharField(default=None, max_length=1000)),
                ('year', models.PositiveSmallIntegerField()),
                ('branch', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=1000)),
                ('description', models.TextField(default=None)),
                ('phone_number', models.BigIntegerField(default=None)),
                ('github', models.URLField(max_length=1000)),
                ('linkedin', models.URLField(max_length=1000)),
                ('gfg', models.URLField(max_length=1000)),
                ('codechef', models.URLField(max_length=1000)),
                ('skills', models.ManyToManyField(to='core.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
