# Generated by Django 2.2 on 2020-04-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200415_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Happened', 'Happened')], default='Upcoming', max_length=100),
        ),
    ]
