# Generated by Django 2.2 on 2020-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='codechef',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gfg',
        ),
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
