# Generated by Django 2.2 on 2020-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200416_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(to='core.Skill'),
        ),
    ]
