# Generated by Django 2.2 on 2020-04-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-year', 'user__first_name'], 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name_plural': 'Tasks'},
        ),
    ]
