# Generated by Django 2.2 on 2020-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200419_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-year', 'position', 'user__first_name'], 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Secretary', '1'), ('Joint-Secretary', '2'), ('Session Head', '3'), ('Social Media Head', '4'), ('Member', '5')], default='5', max_length=100),
        ),
    ]
