# Generated by Django 2.2 on 2020-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200419_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('1', 'Secretary'), ('2', 'Joint-Secretary'), ('3', 'Session Head'), ('4', 'Social Media Head'), ('5', 'Member')], default='5', max_length=100),
        ),
    ]
